coffeescript:
  enabled: true
  config_file: style/coffeescript/coffeelint.json
eslint:
  enabled: true
  config_file: style/javascript/.eslintrc.json
haml:
  enabled: true
  config_file: style/haml/haml.yml
javascript:
  enabled: false
jscs:
  enabled: true
  config_file: style/javascript/.jscsrc
ruby:
  enabled: true
  config_file: style/ruby/.rubocop.yml
scss:
  enabled: true
  config_file: style/sass/.scss-lint.yml
