coffeescript:
  enabled: false
eslint:
  enabled: true
  config_file: style/javascript/.eslintrc.json
  version: 6.3.0
haml:
  enabled: true
  config_file: style/haml/haml.yml
javascript:
  enabled: false
jscs:
  enabled: true
  config_file: style/javascript/.jscsrc
rubocop:
  enabled: true
  config_file: style/ruby/.rubocop.yml
  version: 0.72.0
scss:
  enabled: false
stylelint:
  enabled: true
  config_file: style/sass/.stylelintrc.json
